fix: move to arm64 native steamcmd
Not officially documented, but this is now a thing thanks to steam frame!

diff --git a/src/bootstrap b/src/bootstrap
--- a/src/bootstrap
+++ b/src/bootstrap
@@ -8,7 +8,7 @@
 
 STEAMAPPID=892970
 VOLUME_DIR="/opt/valheim"
-BOX64_LD_LIBRARY_PATH=${VOLUME_DIR}/valheim_server/linux64:${VOLUME_DIR}/steamcmd/linux32:$BOX64_LD_LIBRARY_PATH
+BOX64_LD_LIBRARY_PATH=${VOLUME_DIR}/valheim_server/linux64:$BOX64_LD_LIBRARY_PATH
 BOX64_LOG=${BOX64_LOG:-1}
 BOX64_TRACE_FILE=${VOLUME_DIR}/valheim_server/output.log
 BOX64_TRACE=${BOX64_TRACE:-0}
@@ -103,18 +103,26 @@ write_idlist() {
 
 # Download steam and whatnot
 bootstrap() {
-    if [ ! -d ${VOLUME_DIR}/steamcmd ]; then
+    # Use Valve's native ARM64 steamcmd
+    if [ ! -x ${VOLUME_DIR}/steamcmd/linuxarm64/steamcmd ]; then
         echo "Installing steamcmd..."
+        rm -rf ${VOLUME_DIR}/steamcmd
         mkdir ${VOLUME_DIR}/steamcmd && cd ${VOLUME_DIR}/steamcmd
-        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxf -
+        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linuxarm64.tar.gz" | tar zxf -
         cd - > /dev/null
     fi
 
     # If we exist, make sure we are up to date
-    echo "Ensuring valheinm is up to date..."
+    echo "Ensuring valheim is up to date..."
     cd ${VOLUME_DIR}/steamcmd
-    DEBUGGER="/usr/local/bin/box86" ./steamcmd.sh +@sSteamCmdForcePlatformType linux +force_install_dir ${VOLUME_DIR}/valheim_server +login anonymous +app_update 896660 validate +quit
+    # Force the linux platform, as the server is only published for x86_64
+    ./steamcmd.sh +@sSteamCmdForcePlatformType linux +force_install_dir ${VOLUME_DIR}/valheim_server +login anonymous +app_update 896660 validate +quit
     cd - > /dev/null
+
+    if [ ! -f ${VOLUME_DIR}/valheim_server/valheim_server.x86_64 ]; then
+        echo "Valheim server is not installed, steamcmd failed! Exiting."
+        exit 1
+    fi
 
     # Ensure our world dir exists
     if [ ! -d "${SAVEDIR}" ]; then
